### PR TITLE
Home reviews

### PR DESCRIPTION
**Pull request by Shre26ya**
Added doctor and hospital reviews to the home page.

### CODE REVIEW

**Comment by Chinnu1103** [comment]
Hey @Shre26ya looks good. 
Can you make the reviews in the home page look similar to the doctor details and hospital details? Like its fine if doing that results in the hospital and doctor reviews being vertical..

**Comment by Shre26ya** [comment]
@Chinnu1103 I have added the buttons on the home page, similar to the hospital and doctor details page.

**Comment by Chinnu1103** [comment]
> @Chinnu1103 I have added the buttons on the home page, similar to the hospital and doctor details page.

Great, can you also remove the conflicts?

**Comment by Shre26ya** [comment]
It is done. Please review.

**Review by Chinnu1103 — APPROVED** [review]

**Pull request merged**
